### ISSUE TITLE
ssl-parameters appears twice

### ISSUE THREAD

**Issue by himslm01** [harvester/docs#112]
On this page:

https://github.com/harvester/docs/blob/main/docs/settings/settings.md

ssl-parameters appears twice:

https://docs.harvesterhci.io/v1.0/settings/settings/#ssl-parameters
https://docs.harvesterhci.io/v1.0/settings/settings/#ssl-parameters_1

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/docs/pull/113
