### ISSUE TITLE
rancher-integration suggests docker run as way to install Rancher

### ISSUE THREAD

**Issue by btat** [harvester/docs#123]
Copying over from https://github.com/rancher/docs/issues/3930
cc @tejeev

Summary:
Ref: https://docs.harvesterhci.io/v1.0/rancher/rancher-integration/

Installing Rancher on a cluster in a docker container like this is VERY bad practice and leads to failed and lost environments and easily avoidable customer tickets which can sometimes have no path of recovery for the cluster. This is not supported by us and should suggest good practices of NOT running everything in a docker container, perhaps referring to the methods in the Rancher docs (where they are actually good practice. Even as a quick start, this is bad practice and if it must be the method in this doc, we should also make it clear that his is ONLY a quick start method and should be avoided in anything that is meant to live for any length of time outside of a quick test.

Details:
Install Rancher on K8s without further external encapsulation. The k8s environment should NOT be ephemeral!

**Comment by btat** [comment]
cc @nunix

**Comment by guangbochen** [comment]
This existing one is for quick evaluation purposes, and please feel free to rephrase this page for proper user guidance. Thanks in advance.

**Comment by Tejeev** [comment]
This quick evaluation method gets adopted in production over and over again and has caused uncountable support cases through the years.  Worse yet, customers risk being unable to recover when the environment fails.  We need some strongly worded guidance saying to NOT use this method for any reason but evaluation or take every mention of this method out of every location except for one page specifically and explicitly made for helping people quickly evaluate Rancher with warnings to follow the actual documentation for actual deployments.  I think the later is a better solution.

**Comment by vtrenton** [comment]
Backing up what TJ said above. Using rancher in docker in any production capacity is just asking for trouble. The docs should not reenforce this. We have seen countless cases of production issues surrounding the Rancher in docker method. Rancher in Docker should only be used in testing and demo use cases. Rancher in docker has a lot of serious limitations a true ha setup would not have issue with.

**Comment by guangbochen** [comment]
close as the doc is rephrased via https://github.com/harvester/docs/pull/132, feel free to reopen it if u guys found it requires any further changes, thanks.
