### ISSUE TITLE
Harvester 1.1 documentation for multidisk management still shows screenshots for disks instead of storage

### ISSUE THREAD

**Issue by Roguito** [harvester/docs#244]
https://docs.harvesterhci.io/v1.1/host/ multi disk management section still shows screenshots with the disks tab, where as it is now 'storage'.

in general, more guidance for adding a new disk and the steps involved from host management and creating a new storage class using that disk would be very handy. Perhaps in an FAQ or troubleshooting section.

**Comment by Vicente-Cheng** [comment]
close it due to the above PR being merged.
If you still get confused about multi-disk management feel free to re-open this or create another issue for.

Thanks!
