### ISSUE TITLE
FAQ not up to date?

### ISSUE THREAD

**Issue by gsuess** [harvester/docs#300]
It seem that the FAQ is not up-to-date or lacking details:

![Screenshot 2023-04-11 at 11 32 55](https://user-images.githubusercontent.com/1558575/231120700-ecefbde4-315f-4743-9188-34f4cc171e16.png)

Yet on the dashboard, there is no such button.

**Comment by jillian-maroket** [comment]
You can find the download button on the **Harvester Support** screen of the Harvester UI. [v1.3 FAQ](https://docs.harvesterhci.io/v1.3/faq#how-can-i-access-the-kubeconfig-file-of-the-harvester-cluster)
