### ISSUE TITLE
Note disk size recommendations

### ISSUE THREAD

**Issue by xeruf** [harvester/docs#333]
I have a bootdisk of 110GB and 40TB of data disks, and now get the warning that the bootdisk should be at least 140GB.
Would be good to note that in https://docs.harvesterhci.io/v1.1/install/requirements and explain why such a big bootdisk is required - a Linux system is usually only a few Gigs?

**Comment by xeruf** [comment]
We would really like clarification on this - also can the bootdisk be partitioned to also be usable as storage, or does it have to be a separate medium?

**Comment by LucasSaintarbor** [comment]
@bk201 I see we have the required Disk Capacity listed here https://docs.harvesterhci.io/v1.3/install/requirements. Is https://github.com/harvester/docs/issues/333#issuecomment-1668251593 still a valid question?

**Comment by bk201** [comment]
@LucasSaintarbor I think the requirement answers the question. Feel free to reopen at https://github.com/harvester/harvester/issues if there is any problem.
