### ISSUE TITLE
Add backlink to rancher.com to header

### ISSUE THREAD

**Issue by btat** [harvester/docs#339]
Per feedback from the web team, we should have a link back to https://www.rancher.com for branding/SEO purposes similar to what [Rancher Manager](https://ranchermanager.docs.rancher.com/) has done. The link's label should be "Rancher Home".

**Comment by vickyhella** [comment]
@btat I submitted a PR #367 to add the link to our documentation site, and I was wondering should we also add it to https://harvesterhci.io/ ? Thanks!

**Comment by btat** [comment]
> @btat I submitted a PR #367 to add the link to our documentation site, and I was wondering should we also add it to https://harvesterhci.io/ ? Thanks!

@vickyhella It'd be great if you could add it to https://harvesterhci.io/ as well. Thanks!
