### ISSUE TITLE
Clarify explanation of "Route" configuration for L2VlanNetwork type VM networks

### ISSUE THREAD

**Issue by jeff-radick-suse** [harvester/docs#476]
Some questions from users suggest that adding some explanatory text to the documentation for VM Network configuration may help avoid some confusion on the part of users.

The documentation page https://docs.harvesterhci.io/v1.2/networking/harvester-network/, in the "How to use VLAN network" section, describes the settings in the "Route" panel.  If the user has selected "V2VlanNetwork" as the "type" of network in the "Basic" panel, then the "Route" panel appears and asks the user to select either "Auto(DHCP)" or "Manual", and in each case is required to enter some IP address information.

The potential reason for confusion is as follows.  I will then suggest adding a brief additional comment to explain the reason for this configuration.

The reason that some users may be confused by this configuration panel is that the information entered in this panel does not help Harvester deliver the relevant network traffic, and the user creating any VMs using that network will still have to enter the same information into their guest OS when it is configured.  So, some users have asked "if Harvester doesn't need this to get the network traffic where it needs to go, and if we still have to enter the information into the guest OS, why do we need to enter this information into Harvester?"

The reason for this is that Harvester uses this information to detect whether the VM network you are creating has the desired connectivity on all the nodes.  If it does, then on the main "VM Networks" screen, the "Network connectivity" column will indicate that the network is active, and if it does not, then an error will be indicated.

So, the purpose of this configuration panel is to enable Harvester to provide diagnostic information at a basic level about whether the VM network can reach the desired DHCP server or gateway.

I suggest adding some brief explanation to this effect.  Probably adding a verbose discussion of everything stated above is not necessary, but it can be useful to add some brief statement along the lines of "Harvester uses this information to verify that the configured VM Network has the desired connectivity."  The best exact wording probably depends on where this is added to the document.

I don't think this is vital, but it seems likely to help users understand why they are being asked to supply the information.

**Comment by jillian-maroket** [comment]
@jeff-radick-suse I restructured the existing content (for clarity) and added a note in the last step. The note explains the purpose of the "Route" tab settings as you described in your comment. Please have a look.

Create a VM Network 

1. Go to **Networks** > **VM Networks**.

2. Select **Create**. 

3. Configure the following settings: 
    - Namespace 
    - Name 
    - Description (optional) 

4. On the **Basics** tab, configure the following settings:  
    - Type: Select **L2VlanNetwork**.
    - VLAN ID 
    - Cluster network 

5. On the Route tab, select an option and then specify the related IPv4 addresses.
    - Auto(DHCP): The Harvester network controller retrieves the CIDR and gateway addresses from the DHCP server. You can specify the DHCP server address.
    - Manual: Specify the CIDR and gateway addresses. 

    > **Important**: Harvester uses the information to verify that all nodes can access the VM network you are creating. If that is the case, the *Network connectivity* column on the **VM Networks** screen indicates that the network is active. Otherwise, the screen indicates that an error has occurred.

**Comment by jeff-radick-suse** [comment]
This looks fine to me.  It may be good to get another opinion from somebody who has been around longer and knows the product better.  Possibilities that come to mind that I know about would be Gaurav, Kiefer, or Vicente among the Harvester developers, and Noah Gildersleeve or Mike Russell on the Harvester QA team.  There may well be other good (or better) people to ask.

**Comment by jillian-maroket** [comment]
Thank you for reviewing my draft. I'll create a PR for this and tag some dev/QA folks as reviewers.

**Comment by jeff-radick-suse** [comment]
I will contact an engineer and get back to you, to save you the need to reach out.

**Comment by jillian-maroket** [comment]
This issue has been resolved.
- v1.1: https://docs.harvesterhci.io/v1.1/networking/harvester-network/#create-a-vm-network 
- v1.2: https://docs.harvesterhci.io/v1.2/networking/harvester-network#create-a-vm-network 
- v1.3: https://docs.harvesterhci.io/v1.3/networking/harvester-network#create-a-vm-network
