### ISSUE TITLE
Hint which download provides the vGPU and Guest drivers the AddOn expects

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/docs#553]
For

https://docs.harvesterhci.io/v1.3/advanced/addons/nvidiadrivertoolkit

The vGPU KVM module and guest drivers are usually included in a package called

Linux KVM
All Supported
17.1
Complete vGPU 17.1 package for Linux KVM ALL including supported guest drivers
Mar 26, 2024

<img width="1248" alt="Screenshot 2024-04-23 at 10 26 13 AM" src="https://github.com/harvester/docs/assets/5146963/4bcf2cc9-802d-4e41-b260-518ca9fd4e5d">

Perhaps worth saying
"As of May 2024, the vGPU driver and guest drivers are located inside..."

**Comment by abonillabeeche** [comment]
@ibrokethecloud I'm assuming this is the correct download.

**Comment by jillian-maroket** [comment]
[6013](https://github.com/harvester/harvester/issues/6013) in `harvester/harvester` tracks the same issue.
