### ISSUE TITLE
Change `no-proxy` to `noProxy` 

### ISSUE THREAD

**Issue by votdev** [harvester/docs#560]
The corresponding input field is named `no-proxy` in the UI, but in the [documentation](https://docs.harvesterhci.io/v1.3/advanced/index#http-proxy) `noProxy` notation is always used.

![grafik](https://github.com/harvester/docs/assets/1897962/6e958239-2b91-47b2-91c9-2023b6762f31)

To keep consistency, change `no-proxy` to `noProxy` as it is used in the config as well.

![grafik](https://github.com/harvester/docs/assets/1897962/f8a08659-b9a6-464d-8e59-1004a699076b)

**Comment by innobead** [comment]
@votdev 

If working on the issue already, just assign to the corresponding milestone such as 1.4.0 (the current upcoming feature release).

If requiring backport, add backport labels.
